version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - .:/code

  client_mobile:
    build:
      context: ./application
      dockerfile: mobile.Dockerfile
    volumes:
      - common:/apk

  client_web:
    build:
      context: ./application
      dockerfile: web.Dockerfile
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:5000"
    volumes:
      - common:/apk

volumes:
  common: