version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:5000"
    volumes:
      - .:/code

  client_web:
    build: ./application/web
    depends_on:
      - server
    ports:
      - "8081:5000"
    volumes:
      - .:/apk

volumes:
  common: