version: "2.2"
services:
  database:
    build: ./server/database
    env_file:
      - ./server/database.env
    environment:
      MYSQL_ROOT_PASSWORD: $${password}
      MYSQL_DATABASE: $${database}
    volumes:
      - .:/code
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $${user} --password=$${password}
      interval: 5s
      timeout: 45s
      retries: 40

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - IS_MIGRATION=false #SET TO true when a migration needed
    volumes:
      - .:/code
    stdin_open: true
    tty: true

  client_mobile:
    build:
      context: ./application
      dockerfile: mobile.Dockerfile
    volumes:
      - common:/apk

  client_web:
    build:
      context: ./application
      dockerfile: web.Dockerfile
    depends_on:
      server:
        condition: service_started
      client_mobile:
        condition: service_started
    ports:
      - "8081:5000"
    volumes:
      - common:/apk

  ngrok:
    image: shkoliar/ngrok:latest
    depends_on:
      client_web:
        condition: service_started
    ports:
      - 4551:4551
    links:
      - client_web
    env_file:
      - ./server/database.env
    environment:
      - DOMAIN=client_web
      - PORT=8080
      - AUTH_TOKEN=$${NGROK_AUTH_TOKEN}

volumes:
  common:
