version: "3.3"
services:
  database:
    build: ./server/database
    env_file:
      - ./server/database.env
    environment:
      MYSQL_ROOT_PASSWORD: $${password}
      MYSQL_DATABASE: $${database}
    restart: always
    volumes:
      - .:/code

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - .:/code

# Add a profile for migration

  client_mobile:
    build:
      context: ./application
      dockerfile: mobile.Dockerfile
    volumes:
      - common:/apk

  client_web:
    build:
      context: ./application
      dockerfile: web.Dockerfile
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:5000"
    volumes:
      - common:/apk

volumes:
  common:
