-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 14:59:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

ALTER USER 'root' IDENTIFIED WITH mysql_native_password BY 'password';
flush privileges;
