name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:

  node-format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - name: Start unit testing
        working-directory: ./server
        run: npm test

  flutter-format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter instal
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.3'
          channel: 'stable'
      - name: dependencies
        working-directory: ./application/app_code
        run: flutter pub get
      - name: Format check
        working-directory: ./application/app_code
        run: flutter format --set-exit-if-changed .
      - name: Vulnerabilities analyze
        working-directory: ./application/app_code
        run: flutter analyze .
      - name : Unit testing
        working-directory: ./application/app_code
        run: flutter test

  dockercompose:
    runs-on: ubuntu-latest
    needs: [flutter-format, node-format]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker-compose build && docker-compose up -d
      - name: started ?
        run: docker ps -a
      - name: wait...
        run: sleep 10
      - name: curl check
        run: curl -X GET http://0.0.0.0:8081/client.apk

  mirroring:
    if: github.event_name == 'push'
    needs: dockercompose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}