name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:

  clang-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.10.1
        with:
          clang-format-version: '13'
          check-path: 'server'
          include-regex: '^.*\.(js)$'

  dockercompose:
    runs-on: ubuntu-latest
    needs: clang-format
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker-compose build && docker-compose up -d
      - name: started ?
        run: docker ps -a
      - name: wait...
        run: sleep 10
      - name: curl check
        run: curl -X GET http://0.0.0.0:8081/client.apk

  mirroring:
    if: github.event_name == 'push'
    needs: dockercompose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ secrets.EPI_REPO_URL }}
          ssh_private_key:
            ${{ secrets.EPI_MIRRORING_KEY }}